// src/App.tsx
import { useEffect, useMemo, useState } from 'react';
import { Menu } from './components/Menu';
import { ToolContainer } from './components/ToolContainer';
import { tools, getToolById } from './tools/ToolRegistry';

/**
 * Root application component that manages theme, menu state, and selected tool.
 * Persists theme selection and keeps the selected tool synchronized with the registry.
 *
 * @returns Top-level UI layout combining the menu and active tool.
 */
export function App(): JSX.Element {
  const [theme, setTheme] = useState<'light' | 'dark'>(() => {
    if (typeof window === 'undefined') return 'dark';
    const saved = localStorage.getItem('aviation-tools-theme');
    return (saved === 'light' || saved === 'dark') ? saved : 'dark';
  });
  const [selectedToolId, setSelectedToolId] = useState<string>(() => tools[0]?.id ?? '');
  const [isMenuOpen, setIsMenuOpen] = useState<boolean>(() => (typeof window !== 'undefined' ? window.innerWidth <= 600 : false));

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
    localStorage.setItem('aviation-tools-theme', theme);
  }, [theme]);

  useEffect(() => {
    if (!selectedToolId && tools[0]) {
      setSelectedToolId(tools[0].id);
    }
  }, [selectedToolId]);

  const selectedTool = useMemo(() => getToolById(selectedToolId) ?? tools[0], [selectedToolId]);

  /**
   * Handles selecting a tool from the menu and closes the menu on mobile.
   *
   * @param toolId - Identifier of the tool chosen by the user.
   */
  const handleSelectTool = (toolId: string) => {
    setSelectedToolId(toolId);
    setIsMenuOpen(false);
  };

  return (
    <div id="app">
      <aside id="menu-container" className={isMenuOpen ? 'menu-open' : ''}>
        <Menu
          tools={tools}
          selectedToolId={selectedTool?.id}
          onSelect={handleSelectTool}
          theme={theme}
          onToggleTheme={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
          isOpen={isMenuOpen}
          onToggleMenu={() => setIsMenuOpen((open) => !open)}
        />
      </aside>
      <main id="tool-container">
        <ToolContainer tool={selectedTool} />
      </main>
    </div>
  );
}

// src/app/app.component.ts
import { DOCUMENT } from '@angular/common';
import { ChangeDetectionStrategy, Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { MenuComponent } from './components/menu.component';
import { RouterOutlet } from '@angular/router';
import { ToolDefinition } from './tools/tool-definition';
import { tools } from './components/tool-route.component';

/**
 * Root application component managing theme, menu state, and active tool selection.
 */
@Component({
  selector: 'app-root',
  imports: [MenuComponent, RouterOutlet],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  readonly tools: ToolDefinition[] = tools;
  readonly theme = signal<'light' | 'dark'>('dark');
  readonly isMenuOpen = signal(false);

  private readonly document = inject(DOCUMENT);
  private readonly destroyRef = inject(DestroyRef);

  constructor() {
    if (typeof window !== 'undefined') {
      const updateAppHeight = (): void => {
        const viewportHeight = window.visualViewport?.height ?? window.innerHeight;
        this.document.documentElement.style.setProperty('--app-height', `${Math.round(viewportHeight)}px`);
      };

      updateAppHeight();
      window.addEventListener('resize', updateAppHeight);
      window.visualViewport?.addEventListener('resize', updateAppHeight);
      this.destroyRef.onDestroy(() => {
        window.removeEventListener('resize', updateAppHeight);
        window.visualViewport?.removeEventListener('resize', updateAppHeight);
      });

      const saved = window.localStorage.getItem('aviation-tools-theme');
      if (saved === 'light' || saved === 'dark') {
        this.theme.set(saved);
      }
      this.isMenuOpen.set(window.innerWidth <= 600);
    }
    effect(() => {
      this.document.documentElement.setAttribute('data-theme', this.theme());
      if (typeof window !== 'undefined') {
        window.localStorage.setItem('aviation-tools-theme', this.theme());
      }
    });
  }

  onSelectTool(): void {
    this.isMenuOpen.set(false);
  }

  toggleTheme(): void {
    this.theme.update((current) => (current === 'dark' ? 'light' : 'dark'));
  }

  toggleMenu(): void {
    this.isMenuOpen.update((isOpen) => !isOpen);
  }
}

<div id="app">
  <aside id="menu-container" [class.menu-open]="isMenuOpen()">
    <app-menu
      [tools]="tools"
      [theme]="theme()"
      [isOpen]="isMenuOpen()"
      (selectTool)="onSelectTool()"
      (toggleTheme)="toggleTheme()"
      (toggleMenu)="toggleMenu()"
    ></app-menu>
  </aside>
  <main id="tool-container">
    <router-outlet></router-outlet>
  </main>
</div>
