// src/app/components/tool-container.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { ToolDefinition } from '../tools/tool-definition';

/**
 * Renders the active tool component or a loading state when none is selected.
 */
@Component({
  selector: 'app-tool-container',
  imports: [CommonModule],
  templateUrl: './tool-container.component.html',
  styleUrls: ['./tool-container.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToolContainerComponent {
  readonly tool = input<ToolDefinition | undefined>();
}

@if (tool(); as selectedTool) {
  <div class="tool-wrapper">
    <ng-container *ngComponentOutlet="selectedTool.component"></ng-container>
  </div>
} @else {
  <div class="loading">
    <div class="spinner"></div>
    <p>Select a tool to get started.</p>
  </div>
}

// src/components/ToolContainer.tsx
import { ITool } from '../tools/ITool';

/**
 * Props for {@link ToolContainer}.
 */
interface ToolContainerProps {
  tool?: ITool;
}

/**
 * Renders the active tool component or a loading state when no tool is selected yet.
 *
 * @param props - Contains the active tool definition to render.
 * @returns Wrapper element hosting the selected tool component.
 */
export function ToolContainer({ tool }: ToolContainerProps): JSX.Element {
  if (!tool) {
    return (
      <div className="loading">
        <div className="spinner"></div>
        <p>Select a tool to get started.</p>
      </div>
    );
  }

  const ToolComponent = tool.Component;

  return (
    <div className="tool-wrapper" key={tool.id}>
      <ToolComponent />
    </div>
  );
}
