// src/app/tools/turn-calculator/turn-calculator.component.ts
﻿import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, ElementRef, ViewChild, computed, signal } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { ToolDefinition } from '../tool-definition';

export interface TurnResult {
  radiusMeters: number;
  time360Seconds: number;
}

/**
 * Calculates turn radius and time for a full 360° turn given speed and bank angle.
 *
 * @param speedKnots - True airspeed in knots.
 * @param bankAngle - Bank angle in degrees.
 * @returns Turn radius in meters and time for a complete turn in seconds.
 */
/**
 * UI component that computes turn performance metrics for a selected bank angle.
 */
@Component({
  selector: 'app-turn-calculator',
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './turn-calculator.component.html',
  styleUrls: ['../tool-shared.css', './turn-calculator.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TurnCalculatorComponent {
  readonly speedControl = new FormControl('', { nonNullable: true });
  readonly bankAngleControl = new FormControl('', { nonNullable: true });
  readonly result = signal<TurnResult | null>(null);

  @ViewChild('resultRef') resultRef?: ElementRef<HTMLDivElement>;

  calculate(): void {
    const speedValue = parseFloat(this.speedControl.value);
    const bankValue = parseFloat(this.bankAngleControl.value);

    if (Number.isNaN(speedValue) || Number.isNaN(bankValue)) {
      alert('Please fill in all fields with valid numbers.');
      return;
    }

    if (speedValue <= 0) {
      alert('Speed must be greater than 0.');
      return;
    }

    if (bankValue <= 0 || bankValue >= 90) {
      alert('Bank angle must be between 0 and 90 degrees.');
      return;
    }

    this.result.set(this.calculateTurn(speedValue, bankValue));
    this.scrollToResult();
  }

  calculateTurn(speedKnots: number, bankAngle: number): TurnResult {
    if (bankAngle === 0 || bankAngle >= 90) {
      return { radiusMeters: Infinity, time360Seconds: Infinity };
    }

    const speedMps = speedKnots * 0.514444;
    const bankRad = (bankAngle * Math.PI) / 180;
    const radius = (speedMps * speedMps) / (9.81 * Math.tan(bankRad));
    const turnRateDegPerSec = ((9.81 * Math.tan(bankRad)) / speedMps) * (180 / Math.PI);
    const time360 = 360 / turnRateDegPerSec;

    return {
      radiusMeters: Math.round(radius),
      time360Seconds: Math.round(time360),
    };
  }

  readonly turnRateDegPerSec = computed(() => {
    const current = this.result();
    return current ? 360 / current.time360Seconds : null;
  });

  readonly interpretation = computed(() => {
    const rate = this.turnRateDegPerSec();
    if (rate === null) return '';
    if (rate >= 2.9 && rate <= 3.1) {
      return 'This is approximately a standard rate turn (3°/sec).';
    }
    return rate > 3.1
      ? 'This is faster than a standard rate turn.'
      : 'This is slower than a standard rate turn.';
  });

  formatTurnTime(): string {
    const current = this.result();
    if (!current) return '-';
    const minutes = Math.floor(current.time360Seconds / 60);
    const seconds = Math.round(current.time360Seconds % 60);
    return `${minutes}m ${seconds}s`;
  }

  private scrollToResult(): void {
    const element = this.resultRef?.nativeElement;
    if (!element) return;
    setTimeout(() => {
      try {
        element.scrollIntoView({ behavior: 'smooth', block: 'start' });
      } catch {
        element.scrollIntoView();
      }
    }, 0);
  }
}

/**
 * Tool metadata used by the application registry.
 */
export const turnCalculatorTool: ToolDefinition = {
  id: 'turn-calculator',
  name: 'Turn Calculator',
  description: 'Calculate turn radius and rate based on speed and bank angle',
  component: TurnCalculatorComponent,
};

﻿<div class="tool-content">
  <h2>Turn Calculator</h2>
  <p class="tool-description">
    Calculate turn performance including turn radius and time to complete a 360° turn. Useful
    for planning holds, procedure turns, and traffic patterns.
  </p>

  <div class="input-group">
    <label for="speed">True Airspeed (kt):</label>
    <input
      type="number"
      id="speed"
      placeholder="e.g., 120"
      step="1"
      min="1"
      [formControl]="speedControl"
      (keydown.enter)="calculate()"
    >
  </div>

  <div class="input-group">
    <label for="bank-angle">Bank Angle (°):</label>
    <input
      type="number"
      id="bank-angle"
      placeholder="e.g., 15"
      step="1"
      min="1"
      max="89"
      [formControl]="bankAngleControl"
      (keydown.enter)="calculate()"
    >
    <small>Typical: 15° (standard rate), 30° (steep), 45° (very steep)</small>
  </div>

  <button class="btn-primary" (click)="calculate()">Calculate</button>

  @if (result(); as currentResult) {
    <div #resultRef class="result">
      <h3>Results:</h3>
      <div class="result-grid">
        <div class="result-value">
          <span class="label">Turn Radius:</span>
          <span id="turn-radius" class="value">{{ currentResult.radiusMeters.toLocaleString() }}</span>
          <span class="unit">m</span>
        </div>
        <div class="result-value">
          <span class="label">360° Turn Time:</span>
          <span id="turn-time" class="value">{{ formatTurnTime() }}</span>
        </div>
        <div class="result-value">
          <span class="label">Turn Rate:</span>
          <span id="turn-rate" class="value">{{ turnRateDegPerSec()?.toFixed(2) }}</span>
          <span class="unit">°/sec</span>
        </div>
      </div>
      <div class="result-info" [class.success]="turnRateDegPerSec() && turnRateDegPerSec() >= 2.9 && turnRateDegPerSec() <= 3.1">
        <p id="turn-interpretation">{{ interpretation() }}</p>
      </div>
    </div>
  }
</div>

// src/tools/TurnCalculator.tsx
import { useEffect, useRef, useState } from 'react';
import { ITool } from './ITool';

export interface TurnResult {
  radiusMeters: number;
  time360Seconds: number;
}

/**
 * Calculates turn radius and time for a full 360° turn given speed and bank angle.
 *
 * @param speedKnots - True airspeed in knots.
 * @param bankAngle - Bank angle in degrees.
 * @returns Turn radius in meters and time for a complete turn in seconds.
 */
export function calculateTurn(speedKnots: number, bankAngle: number): TurnResult {
  if (bankAngle === 0 || bankAngle >= 90) {
    return { radiusMeters: Infinity, time360Seconds: Infinity };
  }

  const speedMps = speedKnots * 0.514444;
  const bankRad = (bankAngle * Math.PI) / 180;
  const radius = (speedMps * speedMps) / (9.81 * Math.tan(bankRad));
  const turnRateDegPerSec = ((9.81 * Math.tan(bankRad)) / speedMps) * (180 / Math.PI);
  const time360 = 360 / turnRateDegPerSec;

  return {
    radiusMeters: Math.round(radius),
    time360Seconds: Math.round(time360),
  };
}

/**
 * UI component that computes turn performance metrics for a selected bank angle.
 *
 * @returns Calculation form with derived metrics.
 */
function TurnCalculatorTool(): JSX.Element {
  const [speed, setSpeed] = useState('');
  const [bankAngle, setBankAngle] = useState('');
  const [result, setResult] = useState<TurnResult | null>(null);
  const resultRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!result || !resultRef.current) return;
    try {
      resultRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
    } catch {
      resultRef.current.scrollIntoView();
    }
  }, [result]);

  const handleCalculate = () => {
    const speedValue = parseFloat(speed);
    const bankValue = parseFloat(bankAngle);

    if (Number.isNaN(speedValue) || Number.isNaN(bankValue)) {
      alert('Please fill in all fields with valid numbers');
      return;
    }

    if (speedValue <= 0) {
      alert('Speed must be greater than 0');
      return;
    }

    if (bankValue <= 0 || bankValue >= 90) {
      alert('Bank angle must be between 0 and 90 degrees');
      return;
    }

    setResult(calculateTurn(speedValue, bankValue));
  };

  const turnRateDegPerSec = result ? 360 / result.time360Seconds : null;
  const interpretation =
    turnRateDegPerSec === null
      ? ''
      : turnRateDegPerSec >= 2.9 && turnRateDegPerSec <= 3.1
        ? 'This is approximately a standard rate turn (3°/sec).'
        : turnRateDegPerSec > 3.1
          ? 'This is faster than a standard rate turn.'
          : 'This is slower than a standard rate turn.';

  return (
    <div className="tool-content">
      <h2>Turn Calculator</h2>
      <p className="tool-description">
        Calculate turn performance including turn radius and time to complete a 360° turn. Useful
        for planning holds, procedure turns, and traffic patterns.
      </p>

      <div className="input-group">
        <label htmlFor="speed">True Airspeed (kt):</label>
        <input
          type="number"
          id="speed"
          placeholder="e.g., 120"
          step="1"
          min="1"
          value={speed}
          onChange={(e) => setSpeed(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleCalculate()}
        />
      </div>

      <div className="input-group">
        <label htmlFor="bank-angle">Bank Angle (°):</label>
        <input
          type="number"
          id="bank-angle"
          placeholder="e.g., 15"
          step="1"
          min="1"
          max="89"
          value={bankAngle}
          onChange={(e) => setBankAngle(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleCalculate()}
        />
        <small>Typical: 15° (standard rate), 30° (steep), 45° (very steep)</small>
      </div>

      <button className="btn-primary" onClick={handleCalculate}>Calculate</button>

      {result && (
        <div ref={resultRef} className="result">
          <h3>Results:</h3>
          <div className="result-grid">
            <div className="result-value">
              <span className="label">Turn Radius:</span>
              <span id="turn-radius" className="value">{result.radiusMeters.toLocaleString()}</span>
              <span className="unit">m</span>
            </div>
            <div className="result-value">
              <span className="label">360° Turn Time:</span>
              <span id="turn-time" className="value">
                {(() => {
                  const minutes = Math.floor(result.time360Seconds / 60);
                  const seconds = Math.round(result.time360Seconds % 60);
                  return `${minutes}m ${seconds}s`;
                })()}
              </span>
            </div>
            <div className="result-value">
              <span className="label">Turn Rate:</span>
              <span id="turn-rate" className="value">{turnRateDegPerSec?.toFixed(2)}</span>
              <span className="unit">°/sec</span>
            </div>
          </div>
          <div className={`result-info ${turnRateDegPerSec && turnRateDegPerSec >= 2.9 && turnRateDegPerSec <= 3.1 ? 'success' : ''}`}>
            <p id="turn-interpretation">{interpretation}</p>
          </div>
        </div>
      )}
    </div>
  );
}

/**
 * Tool metadata used by the application registry.
 */
export const turnCalculatorTool: ITool = {
  id: 'turn-calculator',
  name: 'Turn Calculator',
  description: 'Calculate turn radius and rate based on speed and bank angle',
  Component: TurnCalculatorTool,
};
